# Generated by Django 4.0.5 on 2022-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certif',
            field=models.CharField(default='Certificate', max_length=255),
        ),
    ]
